#!/bin/bash
# libs=""
# libz=""
# for fullfile in ./*.o; do
#     filename=$(basename "$fullfile")
#     filename="${filename%.*}"
#     ar crf "lib/lib${filename}.a" "${filename}.o"
#     libs+=" -llib${filename}"
#     libz+=" lib${filename}.a"
# done
# g++ main.o -L./lib $libs -o simulate
ar rvs libsim.a *.o
g++ -fopenmp -O3 -lboost_system -lboost_filesystem -lboost_program_options main.o libsim.a -o simulate
